name: Update Config Gist

on:
  schedule:
    - cron: '0 * * * *' # Каждый час
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Configs
        run: python fetch_configs.py "testdevice"

      - name: Update Gist
        uses: gnikyt/gists-action@v2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistID: b715448f4378d930d82c5e6b6921c8e5
          fileNames: 'configs.txt'
          filePaths: './configs.txt'
          gistDescription: 'Обновление конфигов: ${{ github.run_number }}'
          
