      - name: Update Gist
        env:
          # Здесь используем секрет, который вы создали
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          # Превращаем содержимое файла в JSON-формат для API
          # И отправляем через API GitHub
          curl -L \
            -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"files": {"configs.txt": {"content": "'$(cat configs.txt | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')'"}}}' \
            https://api.github.com/gists/b715448f4378d930d82c5e6b6921c8e5
